export const quotes = [
	["Price is what you pay. Value is what you get.", "Warren Buffett"],
	["We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.", "Warren Buffett"],
	["It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", "Warren Buffett"],
	["Someone's sitting in the shade today because someone planted a tree a long time ago", "Warren Buffett"],
	["If you aren't willing to own a stock for ten years, don't even think about owning it for ten minutes.", "Warren Buffett"],
	["Our favorite holding period is forever.", "Warren Buffett"],
	["I never attempt to make money on the stock market. I buy on the assumption that they could close the market the next day and not reopen it for five years.", "Warren Buffett"],
	["The most important quality for an investor is temperament, not intellect.", "Warren Buffett"],
	["Success in investing doesn't correlate with IQ ... what you need is the temperament to control the urges that get other people into trouble in investing.", "Warren Buffett"],
	["Wall Street is the only place that people ride to in a Rolls Royce to get advice from those who take the subway.", "Warren Buffett"],
	["The years ahead will occasionally deliver major market declines ... No one can tell you when these traumas will occur.", "Warren Buffett"],
	["Predicting rain doesn't count, building the ark does.", "Warren Buffett"],
	["The best chance to deploy capital is when things are going down.", "Warren Buffett"],
	["... the worst investment you can have is cash... Cash is going to become worth less over time. But good businesses are going to become worth more over time.", "Warren Buffett"],
	["If you like spending six to eight hours per week working on investments, do it. If you don't, then dollar-cost average into index funds.", "Warren Buffett"],
	["Buy into a company because you want to own it, not because you want the stock to go up.", "Warren Buffett"],
	["Never invest in a business you cannot understand.", "Warren Buffett"],
	["Risk comes from not knowing what you're doing.", "Warren Buffett"],
	["The most important investment you can make is in yourself.", "Warren Buffett"],
	["In the 20th century, the United States endured two world wars and other traumatic and expensive military conflicts; the Depression; a dozen or so recessions and financial panics; oil shocks; a flu epidemic; and the resignation of a disgraced president. Yet the Dow rose from 66 to 11,497.", "Warren Buffett"],
	[" I continue to believe that short-term market forecasts are poison and should be kept locked up in a safe place, away from children and also from grown-ups who behave in the market like children.", "Warren Buffett"],
	["Being a contrarian isn't the key but being a crowd follower isn't either. You need to detach yourself emotionally.", "Warren Buffett"],
	["For 240 years it's been a terrible mistake to bet against America, and now is no time to start.", "Warren Buffett"],
	["American business -- and consequently a basket of stocks -- is virtually certain to be worth far more in the years ahead.", "Warren Buffett"],
	["Speculation is most dangerous when it looks easiest.", "Warren Buffett"],
	["What we learn from history is that people don't learn from history.", "Warren Buffett"],
	[`There is nothing wrong with a 'know nothing' investor who realizes it. The problem is when you are a 'know nothing' investor but you think you know something.`, "Warren Buffett"],
	["If you're in the luckiest 1% of humanity, you owe it to the rest of humanity to think about the other 99%.", "Warren Buffett"],
	["You could take all the gold that's ever been mined, and it would fill a cube 67 feet in each direction. For what it's worth at current gold prices, you could buy -- not some -- all of the farmland in the United States. Plus, you could buy 10 ExxonMobils, plus have $1 trillion of walking-around money. Or you could have a big cube of metal. Which would you take? Which is going to produce more value?", "Warren Buffett"],
	["Among the various propositions offered to you, if you invested in a very low cost index fund -- where you don't put the money in at one time, but average in over 10 years -- you'll do better than 90% of people who start investing at the same time.", "Warren Buffett"],
	["Just pick a broad index like the S&P 500. Don't put your money in all at once; do it over a period of time.", "Warren Buffett"],
	["It is not necessary to do extraordinary things to get extraordinary results.", "Warren Buffett"],
	["By periodically investing in an index fund, for example, the know - nothing investor can actually outperform most investment professionals.Paradoxically, when 'dumb' money acknowledges its limitations, it ceases to be dumb.", "Warren Buffett"],
	["Don't look for the needle in the haystack. Just buy the haystack!", "Jack Bogle"],
	["The greatest enemy of a good plan is the dream of a perfect plan. Stick to the good plan.", "Jack Bogle"],
	["The two greatest enemies of the equity fund investor are expenses and emotions.", "Jack Bogle"],
	["Owning the stock market over the long term is a winner's game, but attempting to beat the market is a loser's game.", "Jack Bogle"],
	["Time makes more converts than reason.", "Jack Bogle"],
	["The winning formula for success in investing is owning the entire stock market through an index fund, and then doing nothing. Just stay the course.", "Jack Bogle"],
	["Time is your friend; impulse is your enemy.", "Jack Bogle"],
	["The miracle of compounding returns is overwhelmed by the tyranny of compounding costs.", "Jack Bogle"],
	["Of 1,028 stock recommendations made by the typical brokerage firm during the first quarter of 2001 (the peak of the bull market), only 7 were 'sell' recommendations.", "Jack Bogle"],
	["The index fund is a sensible, serviceable method for obtaining the market's rate of return with absolutely no effort and minimal expense.", "Jack Bogle"],
	["Investing is not nearly as difficult as it looks. Successful investing involves doing a few things right and avoiding serious mistakes.", "Jack Bogle"],
	["Know what you own, and know why you own it.", "Peter Lynch"],
	["Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", "Paul Samuelson"],
	["You get recessions, you have stock market declines. If you don't understand that's going to happen, then you're not ready, you won't do well in the markets.", "Peter Lynch"],
	["Debt erases freedom more surely than anything else", "Merryn Somerset Webb"],
	["They say it is better to be poor and happy than rich and miserable, but how about a compromise like moderately rich and just moody?", "Princess Diana"],
	// ["quote", "person"],
	// ["quote", "person"],
	// ["quote", "person"],
];